// <auto-generated />
using ColourAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ColourAPI.Migrations
{
    [DbContext(typeof(ColourContext))]
    partial class ColourContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("ColourAPI.Models.Colour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ColourName")
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.ToTable("Color");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColourName = "Red"
                        },
                        new
                        {
                            Id = 2,
                            ColourName = "Orange"
                        },
                        new
                        {
                            Id = 3,
                            ColourName = "Yellow"
                        },
                        new
                        {
                            Id = 4,
                            ColourName = "Green"
                        },
                        new
                        {
                            Id = 5,
                            ColourName = "Blue"
                        },
                        new
                        {
                            Id = 6,
                            ColourName = "Pink"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
